{% set version = "1.1.0" %}

package:
  name: effect
  version: {{ version }}

source:
  url: https://github.com/python-effect/effect/archive/{{ version }}.tar.gz
  sha256: 1643b74163ba3a00be434364b1fcc2cb15cbc8f47205f3aa5d97418840738642

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - attrs

test:
  requires:
    - python {{ python_min }}
  imports:
    - effect

about:
  home: https://github.com/python-effect/effect
  license: MIT
  license_file: README.rst
  summary: |
    Effect is a library for helping you write purely functional code by
    isolating the effects (that is, IO or state manipulation) in your code.

extra:
  recipe-maintainers:
    - kalefranz
    - synapticarbors
