{% set version = "0.12.0" %}

package:
  name: effect
  version: '{{ version }}'

source:
  fn: '{{ version }}.tar.gz'
  url: https://github.com/python-effect/effect/archive/{{ version }}.tar.gz
  sha256: 89992e8c2d752d698da9be0ce528f09a8146ab119b52c35b25b5b832b0a54e71

build:
  number: 0

requirements:
  build:
    - python
    - attrs
    - six
  run:
    - python
    - attrs
    - six

test:
  requires:
    - pip
    - pytest
  commands:
    - pip install testtools
    - py.test {{ SRC_DIR }}/effect

about:
  home: https://github.com/python-effect/effect
  license: MIT
  summary: >
    Effect is a library for helping you write purely functional code by
    isolating the effects (that is, IO or state manipulation) in your code.

extra:
  recipe-maintainers:
    - kalefranz
