{% set version = "0.11.0" %}

package:
  name: effect
  version: '{{ version }}'

source:
  fn: '{{ version }}.tar.gz'
  url: https://github.com/python-effect/effect/archive/{{ version }}.tar.gz
  sha256: 1f0e270c93b3d4633eef26943ea334564b29d1747ca00d1be2fa7d9555c1e8d5

build:
  number: 0

requirements:
  build:
    - python
    - attrs
    - six
  run:
    - python
    - attrs
    - six

test:
  requires:
    - pip
    - pytest
  commands:
    - pip install testtools
    - py.test {{ SRC_DIR }}/effect

about:
  home: https://github.com/python-effect/effect
  license: MIT
  summary: >
    Effect is a library for helping you write purely functional code by
    isolating the effects (that is, IO or state manipulation) in your code.

extra:
  recipe-maintainers:
    - kalefranz
