{% set version = "1.0.0" %}

package:
  name: effect
  version: {{ version }}

source:
  url: https://github.com/python-effect/effect/archive/{{ version }}.tar.gz
  sha256: a80442ca3e7aa62e9000cafd2a6499e3f85cfc6205d2b9e993648dbfae91bc53

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - pip
  run:
    - python
    - attrs
    - six

test:
  imports:
    - effect

about:
  home: https://github.com/python-effect/effect
  license: MIT
  license_file: README.rst
  summary: |
    Effect is a library for helping you write purely functional code by
    isolating the effects (that is, IO or state manipulation) in your code.

extra:
  recipe-maintainers:
    - kalefranz
