{% set version = "0.10.1" %}

package:
  name: effect
  version: {{ version }}

source:
  url: https://github.com/python-effect/effect/archive/{{ version }}.tar.gz
  sha256: 4e64ef3fdd5720d70ebc95b53101cd5d682ca4e50afa7af3e109e84c4043d507

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - attrs
    - six

test:
  requires:
    - pip
    - pytest
  commands:
    - pip install testtools
    - py.test {{ SRC_DIR }}/effect

about:
  home: https://github.com/python-effect/effect
  license: MIT
  license_file: README.rst
  summary: |
    Effect is a library for helping you write purely functional code by
    isolating the effects (that is, IO or state manipulation) in your code.

extra:
  recipe-maintainers:
    - kalefranz
