appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: K51KuPn3nNCfAOaSTjuXj/34+DIZ1d9k1k905cvN5/JwjtcDkI/OujsvT+3rFsli7VxE+pKKk2vUde/8/ME9FNaWkVGC/sgXzfbcU74Eh/GQdwFoqSQmskpGiI3a2I5ZkZbXKjNvR2hYChRTI25mNO1hHEkzooHz2H4FL2hOuBVMw5VcOc5q3sjDk+jnckPwkNNSpzB7BPnwP5vPcrEF/7uD2aeSBfom0NK8dnSB6I4UPaRIwti4/or7F4hzCr+OAM2iBKhR1rEJa05EppZq7Wb6H0jMVkK9CyQF54PNTI2g9E7PqJaTHxvhQYyVGO/7z3+BukqysBdjd03Ou7dLLIJAxK2TJa60hd8WiH7U9j8qlzj4AtZCayAcwcQR0XPg0IDkJdQMNeRCio5+vsw9j1GrX+xNzvdikDcumymFUu+PozcWQpwSkZs/ZgDIAgAUAqs/JcvSNOyh/bYVDnkHp+hRjVs7TO1MZBOAaKgC5z2M3/v6KK4z22did0UqH/O9Xm2O3lPiuzGvoZwsbah/boFffHjvQsOjNtUTauXYZRRga4Vons0IQVloktHl3Wd5KbEwer3n8ypRDO84+Ht8nhV/suZj/eKJT3iCGS21uOmm1+SzEi37ul6qfy+wQnDrJBbzapSYTUEZfFui9OwhlXoL7HPqz5U3h1HaklLq8V4=}
