travis:
  secure:
    BINSTAR_TOKEN: DxSDSmHhHByB2Fz5NEdCeR2R+/KBxmKSwb6Im4xtvb4I+TSOSb62uLEdgtYtXWOmxrwG7IO/aaI1e0/D+kMeFSkVwFa2XJE+8K33gaE1ZFapsZboy6yWuAFuDgw2WtTNjj92MRBE69kXc7r0SgJ2EF7X5bigVL09BsRk1++8kaktBcLJupolNZ68zzQ6oIBMHhE8Wi5ZkvIw4CQxrXfEBfWukRKfnuPgRufq7x2AfJVmeoYWZINv1YYDQfYcTdKvVtsOIIoiLIK/qnO81OoodUrn7x4xe6+fX0xLnsn5Hjl0kjxHTsXdudf2YJG8WleJkJTY8pgQ3foAEqScGwe44jW/4DrhiRabUZ93aHHzAFlPEW1EPp2DnulJCHwyKHN1c50EdXmF9uwtfojIjuzR6er4EpDthJSlEWuT/8wurQGIlkOzgc2K3iw/rzOLYzg5gTu5OZrswKJG3xayNu/oWD54WqALvEHpxvur0WcT6FjBvvOjHk7wx2d92LBjO8g+PC/Gc2oY0Yf00ZWdMwW5YelhJKFgmZ2fJh36r67ZWJ9HQNIAW00dmDHQf0b2Mrd1WcZEKo8Zr/b+6VL7Qiacmp6Y+2QUkbXI3kLc6hkwHftaY140y9UQnFeY0mw7k5iq1Or1tVzu9AJ+X5uSSOAa2rLGbS9ycydabWrvusPv92M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
